CREATE DATABASE if not exists PI4;

CREATE TABLE USER_BACKOFFICE (
    ID_USER int PRIMARY KEY auto_increment,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(70) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    STATUS VARCHAR(25),
    GROUP_USER VARCHAR(25)
);

CREATE TABLE TBL_PRODUCT (
    ID_PRODUCT INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    NAME_PRODUCT VARCHAR(200) NOT NULL ,
    RATING_PRODUCT DOUBLE ,
    DESCRIPTION_PRODUCT VARCHAR(2000) NOT NULL ,
    PRICE_PRODUCT DOUBLE NOT NULL ,
    AMOUNT_PRODUCT INT NOT NULL, 
    STATUS VARCHAR(25)
);

CREATE TABLE TBL_PRODUCT_IMAGE (
    IMAGE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    IMAGE_PRODUCT_PATH VARCHAR(2000) NOT NULL ,
    IMAGE_DEFAULT varchar(3),
    ID_PRODUCT INT,
    FOREIGN KEY (ID_PRODUCT) REFERENCES TBL_PRODUCT (ID_PRODUCT)
);

